/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthOnboardingRouteImport } from './routes/auth/onboarding'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppWorkspaceRouteImport } from './routes/_app/workspace'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppWorkspaceIndexRouteImport } from './routes/_app/workspace/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppMileageIndexRouteImport } from './routes/_app/mileage/index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppWorkspaceSettingsRouteImport } from './routes/_app/workspace/settings'
import { Route as AppWorkspaceReportsRouteImport } from './routes/_app/workspace/reports'
import { Route as AppWorkspaceMileageRouteImport } from './routes/_app/workspace/mileage'
import { Route as AppWorkspaceMembersRouteImport } from './routes/_app/workspace/members'
import { Route as AppWorkspaceExpensesRouteImport } from './routes/_app/workspace/expenses'
import { Route as AppWorkspaceApprovalsRouteImport } from './routes/_app/workspace/approvals'
import { Route as AppReportsReportIdRouteImport } from './routes/_app/reports/$reportId'
import { Route as AppExpensesExpenseIdRouteImport } from './routes/_app/expenses/$expenseId'
import { Route as AppAdminMembersRouteImport } from './routes/_app/admin/members'
import { Route as AppAdminApprovalRouteImport } from './routes/_app/admin/approval'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppMileageIndexRoute = AppMileageIndexRouteImport.update({
  id: '/mileage/',
  path: '/mileage/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceSettingsRoute = AppWorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceReportsRoute = AppWorkspaceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceMileageRoute = AppWorkspaceMileageRouteImport.update({
  id: '/mileage',
  path: '/mileage',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceMembersRoute = AppWorkspaceMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceExpensesRoute = AppWorkspaceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceApprovalsRoute = AppWorkspaceApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesExpenseIdRoute = AppExpensesExpenseIdRouteImport.update({
  id: '/expenses/$expenseId',
  path: '/expenses/$expenseId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovalRoute = AppAdminApprovalRouteImport.update({
  id: '/admin/approval',
  path: '/admin/approval',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/home': typeof AppHomeRoute
  '/inbox': typeof AppInboxRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/join/$code': typeof JoinCodeRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/admin/approval': typeof AppAdminApprovalRoute
  '/admin/members': typeof AppAdminMembersRoute
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/workspace/approvals': typeof AppWorkspaceApprovalsRoute
  '/workspace/expenses': typeof AppWorkspaceExpensesRoute
  '/workspace/members': typeof AppWorkspaceMembersRoute
  '/workspace/mileage': typeof AppWorkspaceMileageRoute
  '/workspace/reports': typeof AppWorkspaceReportsRoute
  '/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/mileage/': typeof AppMileageIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/home': typeof AppHomeRoute
  '/inbox': typeof AppInboxRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/join/$code': typeof JoinCodeRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/admin/approval': typeof AppAdminApprovalRoute
  '/admin/members': typeof AppAdminMembersRoute
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/workspace/approvals': typeof AppWorkspaceApprovalsRoute
  '/workspace/expenses': typeof AppWorkspaceExpensesRoute
  '/workspace/members': typeof AppWorkspaceMembersRoute
  '/workspace/mileage': typeof AppWorkspaceMileageRoute
  '/workspace/reports': typeof AppWorkspaceReportsRoute
  '/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/mileage': typeof AppMileageIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/workspace': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workspace': typeof AppWorkspaceRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/join/$code': typeof JoinCodeRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/_app/admin/approval': typeof AppAdminApprovalRoute
  '/_app/admin/members': typeof AppAdminMembersRoute
  '/_app/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/_app/reports/$reportId': typeof AppReportsReportIdRoute
  '/_app/workspace/approvals': typeof AppWorkspaceApprovalsRoute
  '/_app/workspace/expenses': typeof AppWorkspaceExpensesRoute
  '/_app/workspace/members': typeof AppWorkspaceMembersRoute
  '/_app/workspace/mileage': typeof AppWorkspaceMileageRoute
  '/_app/workspace/reports': typeof AppWorkspaceReportsRoute
  '/_app/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/mileage/': typeof AppMileageIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/inbox'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/workspace'
    | '/auth/callback'
    | '/auth/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/join/$code'
    | '/workspaces/new'
    | '/workspaces/'
    | '/admin/approval'
    | '/admin/members'
    | '/expenses/$expenseId'
    | '/reports/$reportId'
    | '/workspace/approvals'
    | '/workspace/expenses'
    | '/workspace/members'
    | '/workspace/mileage'
    | '/workspace/reports'
    | '/workspace/settings'
    | '/expenses/'
    | '/mileage/'
    | '/reports/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/inbox'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/auth/callback'
    | '/auth/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/join/$code'
    | '/workspaces/new'
    | '/workspaces'
    | '/admin/approval'
    | '/admin/members'
    | '/expenses/$expenseId'
    | '/reports/$reportId'
    | '/workspace/approvals'
    | '/workspace/expenses'
    | '/workspace/members'
    | '/workspace/mileage'
    | '/workspace/reports'
    | '/workspace/settings'
    | '/expenses'
    | '/mileage'
    | '/reports'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/home'
    | '/_app/inbox'
    | '/_app/profile'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/workspace'
    | '/auth/callback'
    | '/auth/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/join/$code'
    | '/workspaces/new'
    | '/workspaces/'
    | '/_app/admin/approval'
    | '/_app/admin/members'
    | '/_app/expenses/$expenseId'
    | '/_app/reports/$reportId'
    | '/_app/workspace/approvals'
    | '/_app/workspace/expenses'
    | '/_app/workspace/members'
    | '/_app/workspace/mileage'
    | '/_app/workspace/reports'
    | '/_app/workspace/settings'
    | '/_app/expenses/'
    | '/_app/mileage/'
    | '/_app/reports/'
    | '/_app/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  JoinCodeRoute: typeof JoinCodeRoute
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/': {
      id: '/_app/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mileage/': {
      id: '/_app/mileage/'
      path: '/mileage'
      fullPath: '/mileage/'
      preLoaderRoute: typeof AppMileageIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/settings': {
      id: '/_app/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof AppWorkspaceSettingsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/reports': {
      id: '/_app/workspace/reports'
      path: '/reports'
      fullPath: '/workspace/reports'
      preLoaderRoute: typeof AppWorkspaceReportsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/mileage': {
      id: '/_app/workspace/mileage'
      path: '/mileage'
      fullPath: '/workspace/mileage'
      preLoaderRoute: typeof AppWorkspaceMileageRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/members': {
      id: '/_app/workspace/members'
      path: '/members'
      fullPath: '/workspace/members'
      preLoaderRoute: typeof AppWorkspaceMembersRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/expenses': {
      id: '/_app/workspace/expenses'
      path: '/expenses'
      fullPath: '/workspace/expenses'
      preLoaderRoute: typeof AppWorkspaceExpensesRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/approvals': {
      id: '/_app/workspace/approvals'
      path: '/approvals'
      fullPath: '/workspace/approvals'
      preLoaderRoute: typeof AppWorkspaceApprovalsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/reports/$reportId': {
      id: '/_app/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/$expenseId': {
      id: '/_app/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AppExpensesExpenseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/members': {
      id: '/_app/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/approval': {
      id: '/_app/admin/approval'
      path: '/admin/approval'
      fullPath: '/admin/approval'
      preLoaderRoute: typeof AppAdminApprovalRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppWorkspaceRouteChildren {
  AppWorkspaceApprovalsRoute: typeof AppWorkspaceApprovalsRoute
  AppWorkspaceExpensesRoute: typeof AppWorkspaceExpensesRoute
  AppWorkspaceMembersRoute: typeof AppWorkspaceMembersRoute
  AppWorkspaceMileageRoute: typeof AppWorkspaceMileageRoute
  AppWorkspaceReportsRoute: typeof AppWorkspaceReportsRoute
  AppWorkspaceSettingsRoute: typeof AppWorkspaceSettingsRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceApprovalsRoute: AppWorkspaceApprovalsRoute,
  AppWorkspaceExpensesRoute: AppWorkspaceExpensesRoute,
  AppWorkspaceMembersRoute: AppWorkspaceMembersRoute,
  AppWorkspaceMileageRoute: AppWorkspaceMileageRoute,
  AppWorkspaceReportsRoute: AppWorkspaceReportsRoute,
  AppWorkspaceSettingsRoute: AppWorkspaceSettingsRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppInboxRoute: typeof AppInboxRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppAdminApprovalRoute: typeof AppAdminApprovalRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppExpensesExpenseIdRoute: typeof AppExpensesExpenseIdRoute
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppMileageIndexRoute: typeof AppMileageIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppInboxRoute: AppInboxRoute,
  AppProfileRoute: AppProfileRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppAdminApprovalRoute: AppAdminApprovalRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppExpensesExpenseIdRoute: AppExpensesExpenseIdRoute,
  AppReportsReportIdRoute: AppReportsReportIdRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppMileageIndexRoute: AppMileageIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  JoinCodeRoute: JoinCodeRoute,
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
